name: simple_tetris
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0-163.1.beta <4.0.0'

dependencies:
  audioplayers: ^5.1.0
  avatar_glow: ^2.0.2
  flutter:
    sdk: flutter
  get: ^4.6.5
  get_storage: ^2.1.1
  sqflite: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/audio/
