name: simple_tetris
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0-163.1.beta <4.0.0'

dependencies:
  animated_splash_screen: ^1.3.0
  audioplayers: ^5.1.0
  avatar_glow: ^2.0.2
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.2
  get: ^4.6.5
  get_storage: ^2.1.1
  google_fonts: ^6.0.0
  lottie: ^2.6.0
  sqflite: ^2.3.0
  blur: ^3.0.0
 
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/animated_files/
    - assets/app_icons/
    - assets/audio/
    - assets/images/home/
    - assets/images/top_list/
    - assets/in_app_icons/arrows/
    - assets/in_app_icons/icons/
    - assets/in_app_icons/play/


flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/app_icons/icon4.png"
  
flutter_native_splash:
  color: "#024811"
